// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asobjuqzthhvuzdjaaiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzb2JqdXF6dGhodnV6ZGphYWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDU3NjQsImV4cCI6MjA2ODkyMTc2NH0.G6uPzh8CgjO9TOIxizNbWZWfXGKO7J-8kDbJ7-uU53M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});